import { SCANOPS_USER_CONTEXT } from "./scanOpsInventoryFixtures";
import { getInventoryConnection, pushInventoryEvent, setInventoryConnectionMode } from "./inventorySystemAdapter";

const QUEUE_KEY = "invyra_scanops_sync_queue_v1";
export const SYNC_STATUSES = { LOCAL_SAVED: "LOCAL_SAVED", QUEUED: "QUEUED", SYNCING: "SYNCING", SYNCED: "SYNCED", FAILED: "FAILED", CONFLICT: "CONFLICT", NEEDS_REVIEW: "NEEDS_REVIEW" };
export const SYNC_STATUS_LABELS = { LOCAL_SAVED: "Saved on device", QUEUED: "Waiting to sync", SYNCING: "Syncing now", SYNCED: "Synced", FAILED: "Sync failed", CONFLICT: "Conflict found", NEEDS_REVIEW: "Needs review" };
const NON_SYNC_PREFIXES = ["SYNC_", "INVENTORY_SYNC_", "INVENTORY_PULL_", "INVENTORY_PUSH_", "OFFLINE_MODE_", "ONLINE_MODE_", "LOCAL_EVENT_SAVED"];
function read() { if (typeof window === "undefined") return []; try { const raw = window.localStorage.getItem(QUEUE_KEY); return raw ? JSON.parse(raw) : []; } catch { return []; } }
function write(queue) { if (typeof window === "undefined") return; try { window.localStorage.setItem(QUEUE_KEY, JSON.stringify(queue)); } catch {} }
function makeId(prefix) { return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`; }
function hist(status, message, extra = {}) { return { status, label: SYNC_STATUS_LABELS[status] || status, message, at: new Date().toISOString(), ...extra }; }
function payloadSummary(event) { const item = event?.item_name || event?.itemName || event?.sku || event?.barcode || event?.plu || event?.task_id || "Scanner event"; return `${event?.event_type || "EVENT"} · ${item}`; }
function requiresSyncReview(event) {
  const type = String(event?.event_type || "");
  const status = String(event?.status || "").toLowerCase();
  return type.endsWith("_SUPERVISOR_REVIEW_REQUIRED") || status.includes("review_required") || event?.supervisor_review_required === true;
}
export function shouldQueueInventoryEvent(eventType) { const value = String(eventType || ""); return Boolean(value) && !NON_SYNC_PREFIXES.some((prefix) => value.startsWith(prefix)); }
export function getNetworkMode() { return getInventoryConnection().mode || "online"; }
export function setNetworkMode(mode) { return setInventoryConnectionMode(mode); }
export function getSyncQueue() { return read(); }
export function saveSyncQueue(queue) { write(queue); return queue; }
export function getSyncSummary() { const q = read(); const count = (s) => q.filter((e) => e.status === s).length; return { total: q.length, queued: count(SYNC_STATUSES.QUEUED), syncing: count(SYNC_STATUSES.SYNCING), synced: count(SYNC_STATUSES.SYNCED), failed: count(SYNC_STATUSES.FAILED), conflict: count(SYNC_STATUSES.CONFLICT), needsReview: count(SYNC_STATUSES.NEEDS_REVIEW) }; }
export function recordEventForInventorySync(event) { if (!event || event.sync_exempt || !shouldQueueInventoryEvent(event.event_type)) return null; const existing = read().find((e) => e.localEventId === event.event_id); if (existing) return existing; const needsReview = requiresSyncReview(event); const initialStatus = needsReview ? SYNC_STATUSES.NEEDS_REVIEW : SYNC_STATUSES.LOCAL_SAVED; const record = { id: makeId("sync"), localEventId: event.event_id, inventoryEventId: null, eventType: event.event_type, sourceModule: event.source_module || "ScanOps", status: initialStatus, statusLabel: SYNC_STATUS_LABELS[initialStatus], priority: event.task_priority || event.priority || (needsReview ? "High" : "Normal"), createdAt: new Date().toISOString(), lastAttemptAt: null, attemptCount: 0, deviceId: event.scanner_id || SCANOPS_USER_CONTEXT.scanner_id, locationId: event.location_id || SCANOPS_USER_CONTEXT.location_id, userRole: event.role || SCANOPS_USER_CONTEXT.role, payloadSummary: payloadSummary(event), payload: event, failureReason: needsReview ? "Supervisor review required before Inventory applies movement." : null, syncHistory: [hist(initialStatus, needsReview ? "Saved on this scanner and held for supervisor review." : "Saved on this scanner.")] }; write([record, ...read()]); if (needsReview) return record; return getNetworkMode() === "offline" ? queueSyncEvent(record.id, "Scanner is offline. Waiting to sync with Invyra Inventory.") : attemptSync(record.id); }
export function queueSyncEvent(syncId, reason = "Waiting to sync with Invyra Inventory.") { let next = null; const updated = read().map((entry) => { if (entry.id !== syncId) return entry; next = { ...entry, status: SYNC_STATUSES.QUEUED, statusLabel: SYNC_STATUS_LABELS.QUEUED, failureReason: null, syncHistory: [hist(SYNC_STATUSES.QUEUED, reason), ...(entry.syncHistory || [])] }; return next; }); write(updated); return next; }
export function attemptSync(syncId) { const queue = read(); const existing = queue.find((e) => e.id === syncId); if (!existing) return null; if (existing.status === SYNC_STATUSES.SYNCED) return existing; const syncing = { ...existing, status: SYNC_STATUSES.SYNCING, statusLabel: SYNC_STATUS_LABELS.SYNCING, lastAttemptAt: new Date().toISOString(), attemptCount: (existing.attemptCount || 0) + 1, syncHistory: [hist(SYNC_STATUSES.SYNCING, "Sync attempt started."), ...(existing.syncHistory || [])] }; write(queue.map((e) => e.id === syncId ? syncing : e)); if (syncing.payload?.forceSyncConflict) return markSyncConflict(syncId, "Conflict placeholder: inventory changed since scanner action."); const result = pushInventoryEvent(syncing); return result.ok ? markSyncSucceeded(syncId, result.inventoryEventId, result.message || "Synced to Invyra Inventory.") : markSyncFailed(syncId, result.error || "Inventory sync failed."); }
export function retrySyncEvent(syncId) { const existing = read().find((e) => e.id === syncId); if (!existing) return null; if ([SYNC_STATUSES.SYNCED, SYNC_STATUSES.NEEDS_REVIEW].includes(existing.status)) return existing; return attemptSync(syncId); }
export function retryAllSyncEvents() { return read().filter((e) => [SYNC_STATUSES.QUEUED, SYNC_STATUSES.FAILED, SYNC_STATUSES.CONFLICT, SYNC_STATUSES.NEEDS_REVIEW].includes(e.status)).map((e) => retrySyncEvent(e.id)); }
export function markSyncSucceeded(syncId, inventoryEventId, message = "Synced to Invyra Inventory.") { let next = null; const updated = read().map((e) => { if (e.id !== syncId) return e; next = { ...e, inventoryEventId, status: SYNC_STATUSES.SYNCED, statusLabel: SYNC_STATUS_LABELS.SYNCED, failureReason: null, syncedAt: new Date().toISOString(), syncHistory: [hist(SYNC_STATUSES.SYNCED, message, { inventoryEventId }), ...(e.syncHistory || [])] }; return next; }); write(updated); return next; }
export function markSyncFailed(syncId, reason = "Sync failed.") { let next = null; const updated = read().map((e) => { if (e.id !== syncId) return e; next = { ...e, status: SYNC_STATUSES.FAILED, statusLabel: SYNC_STATUS_LABELS.FAILED, failureReason: reason, syncHistory: [hist(SYNC_STATUSES.FAILED, reason), ...(e.syncHistory || [])] }; return next; }); write(updated); return next; }
export function markSyncConflict(syncId, reason = "Conflict found. Needs review.") { let next = null; const updated = read().map((e) => { if (e.id !== syncId) return e; next = { ...e, status: SYNC_STATUSES.CONFLICT, statusLabel: SYNC_STATUS_LABELS.CONFLICT, failureReason: reason, syncHistory: [hist(SYNC_STATUSES.CONFLICT, reason), ...(e.syncHistory || [])] }; return next; }); write(updated); return next; }
export function resetSyncQueue() { write([]); return []; }
