export const SCANOPS_USER_CONTEXT = {
  user_id: "staff_001",
  role: "Staff",
  user_name: "Sarah M.",
  scanner_id: "SCANOPS_001",
  location_id: "store_001",
  department: "Grocery",
};

export const REPLENISHMENT_SCAN_ITEM = {
  id: "replenish-coke-125",
  name: "Coke No Sugar 1.25L",
  sku: "930000000001",
  barcode: "930000000001",
  shelf_stock: 0,
  backroom_stock: 18,
  pending_delivery_qty: 0,
  minimum_shelf_qty: 6,
  aisle: "Aisle 4",
  bay: "Bay 2",
  shelf: "Shelf 3",
  planogram_status: "OK",
};

export const GAP_SCAN_SCENARIOS = [
  {
    id: "backroom-available",
    buttonLabel: "Backroom available",
    name: "Coke No Sugar 1.25L",
    sku: "930000000001",
    barcode: "930000000001",
    shelf_stock: 0,
    backroom_stock: 18,
    pending_delivery_qty: 0,
    minimum_shelf_qty: 6,
    aisle: "Aisle 4",
    bay: "Bay 2",
    shelf: "Shelf 3",
    planogram_status: "OK",
  },
  {
    id: "true-out-of-stock",
    buttonLabel: "True out of stock",
    name: "Dairy Milk Chocolate 180g",
    sku: "930000000002",
    barcode: "930000000002",
    shelf_stock: 0,
    backroom_stock: 0,
    pending_delivery_qty: 0,
    minimum_shelf_qty: 8,
    aisle: "Aisle 7",
    bay: "Bay 5",
    shelf: "Shelf 2",
    planogram_status: "OK",
  },
  {
    id: "supplier-pending",
    buttonLabel: "Supplier pending",
    name: "Greek Yoghurt 1kg",
    sku: "930000000003",
    barcode: "930000000003",
    shelf_stock: 0,
    backroom_stock: 0,
    pending_delivery_qty: 24,
    pending_delivery_eta: "Tomorrow",
    minimum_shelf_qty: 5,
    aisle: "Aisle 2",
    bay: "Bay 8",
    shelf: "Shelf 1",
    planogram_status: "OK",
  },
  {
    id: "label-planogram-issue",
    buttonLabel: "Label / planogram issue",
    name: "Unknown / Mismatched Shelf Label",
    sku: "UNLINKED-LABEL",
    barcode: "A4-B2-03",
    shelf_stock: null,
    backroom_stock: null,
    pending_delivery_qty: null,
    minimum_shelf_qty: null,
    aisle: "Aisle 4",
    bay: "Bay 2",
    shelf: "Label A4-B2-03",
    planogram_status: "MISMATCH",
    label_issue: true,
  },
];
