export const SCANOPS_USER_CONTEXT = {
  user_id: "staff_001",
  role: "Staff",
  user_name: "Sarah M.",
  scanner_id: "SCANOPS_001",
  location_id: "store_001",
  department: "Grocery",
};

export const REPLENISHMENT_SCAN_ITEM = {
  id: "replenish-coke-125",
  name: "Coke No Sugar 1.25L",
  sku: "930000000001",
  barcode: "930000000001",
  shelf_stock: 0,
  backroom_stock: 18,
  pending_delivery_qty: 0,
  minimum_shelf_qty: 6,
  aisle: "Aisle 4",
  bay: "Bay 2",
  shelf: "Shelf 3",
  planogram_status: "OK",
};

export const GAP_SCAN_SCENARIOS = [
  {
    id: "backroom-available",
    buttonLabel: "Backroom available",
    name: "Coke No Sugar 1.25L",
    sku: "930000000001",
    barcode: "930000000001",
    shelf_stock: 0,
    backroom_stock: 18,
    pending_delivery_qty: 0,
    minimum_shelf_qty: 6,
    aisle: "Aisle 4",
    bay: "Bay 2",
    shelf: "Shelf 3",
    planogram_status: "OK",
  },
  {
    id: "true-out-of-stock",
    buttonLabel: "True out of stock",
    name: "Dairy Milk Chocolate 180g",
    sku: "930000000002",
    barcode: "930000000002",
    shelf_stock: 0,
    backroom_stock: 0,
    pending_delivery_qty: 0,
    minimum_shelf_qty: 8,
    aisle: "Aisle 7",
    bay: "Bay 5",
    shelf: "Shelf 2",
    planogram_status: "OK",
  },
  {
    id: "supplier-pending",
    buttonLabel: "Supplier pending",
    name: "Greek Yoghurt 1kg",
    sku: "930000000003",
    barcode: "930000000003",
    shelf_stock: 0,
    backroom_stock: 0,
    pending_delivery_qty: 24,
    pending_delivery_eta: "Tomorrow",
    minimum_shelf_qty: 5,
    aisle: "Aisle 2",
    bay: "Bay 8",
    shelf: "Shelf 1",
    planogram_status: "OK",
  },
  {
    id: "label-planogram-issue",
    buttonLabel: "Label / planogram issue",
    name: "Unknown / Mismatched Shelf Label",
    sku: "UNLINKED-LABEL",
    barcode: "A4-B2-03",
    shelf_stock: null,
    backroom_stock: null,
    pending_delivery_qty: null,
    minimum_shelf_qty: null,
    aisle: "Aisle 4",
    bay: "Bay 2",
    shelf: "Label A4-B2-03",
    planogram_status: "MISMATCH",
    label_issue: true,
  },
];

export const MARKDOWN_SCAN_ITEM = {
  id: "markdown-yoghurt-1kg",
  name: "Greek Yoghurt 1kg",
  sku: "930000000004",
  barcode: "930000000004",
  current_price: 220,
  currency: "₱",
  expiry_status: "Expires tomorrow",
  expiry_days: 1,
  shelf_stock: 9,
  backroom_stock: 12,
  department: "Dairy",
  aisle: "Aisle 2",
  bay: "Bay 8",
  shelf: "Shelf 1",
  location: "Chilled dairy bay",
};

export const WASTE_SCAN_ITEM = {
  id: "waste-chicken-1kg",
  name: "Chicken Breast 1kg",
  sku: "930000000008",
  barcode: "930000000008",
  unit_cost: 185,
  currency: "₱",
  stock_on_hand: 22,
  department: "Fresh Meat",
  aisle: "Fresh Zone",
  bay: "Meat Case 3",
  shelf: "Tray 2",
  location: "Chilled meat case",
  expiry_status: "Use by today",
  cold_chain_required: true,
};

export const EXPIRY_CHECK_SCENARIOS = [
  {
    id: "dairy-near-expiry",
    buttonLabel: "Dairy · tomorrow",
    name: "Greek Yoghurt 1kg",
    sku: "930000000004",
    barcode: "930000000004",
    current_price: 220,
    currency: "₱",
    department: "Dairy",
    category: "Dairy",
    aisle: "Aisle 2",
    bay: "Bay 8",
    shelf: "Shelf 1",
    location: "Chiller A / Bay 2",
    stock_on_hand: 21,
    shelf_stock: 9,
    backroom_stock: 12,
    expiry_date: "2026-05-06",
    freshness_default: "near_expiry",
    cold_chain_required: true,
  },
  {
    id: "meat-expired",
    buttonLabel: "Meat · expired",
    name: "Chicken Breast 1kg",
    sku: "930000000008",
    barcode: "930000000008",
    current_price: 265,
    currency: "₱",
    department: "Fresh Meat",
    category: "Meat",
    aisle: "Fresh Zone",
    bay: "Meat Case 3",
    shelf: "Tray 2",
    location: "Chilled meat case",
    stock_on_hand: 22,
    shelf_stock: 8,
    backroom_stock: 14,
    expiry_date: "2026-05-04",
    freshness_default: "needs_supervisor_review",
    cold_chain_required: true,
  },
  {
    id: "produce-condition",
    buttonLabel: "Produce · condition",
    name: "Strawberries 250g",
    sku: "930000000009",
    barcode: "930000000009",
    current_price: 155,
    currency: "₱",
    department: "Produce",
    category: "Produce",
    aisle: "Fresh Zone",
    bay: "Produce Table 1",
    shelf: "Crate 4",
    location: "Produce table / front left",
    stock_on_hand: 18,
    shelf_stock: 18,
    backroom_stock: 0,
    expiry_date: "",
    freshness_default: "poor_appearance",
    cold_chain_required: false,
  },
];

export const EXPIRY_CHECK_SCAN_ITEM = EXPIRY_CHECK_SCENARIOS[0];
