import { SCANOPS_USER_CONTEXT } from "./scanOpsInventoryFixtures";
import { recordEventForInventorySync } from "./scanOpsSync";
import { buildEventIdentity, getScanOpsSession } from "./scanOpsSession";

const STORAGE_KEY = "invyra_scanops_events_v1";

function safeReadEvents() {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch (error) {
    console.warn("Unable to read ScanOps events", error);
    return [];
  }
}

function safeWriteEvents(events) {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(events));
  } catch (error) {
    console.warn("Unable to persist ScanOps events", error);
  }
}

function makeId(prefix) {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

export const SCANOPS_EVENT_TYPES = {
  REPLENISHMENT_CREATED: "REPLENISHMENT_CREATED",
  REPLENISHMENT_COMPLETED: "REPLENISHMENT_COMPLETED",
  GAP_CONFIRMED: "GAP_CONFIRMED",
  REORDER_REQUESTED: "REORDER_REQUESTED",
  SHELF_LABEL_ISSUE_FLAGGED: "SHELF_LABEL_ISSUE_FLAGGED",
  PLANOGRAM_ISSUE_FLAGGED: "PLANOGRAM_ISSUE_FLAGGED",
  SUPPLIER_PENDING_CONFIRMED: "SUPPLIER_PENDING_CONFIRMED",
  REPLENISHMENT_CANCELLED: "REPLENISHMENT_CANCELLED",
  STOCK_COUNT_SESSION_CREATED: "STOCK_COUNT_SESSION_CREATED",
  STOCK_COUNT_SESSION_STARTED: "STOCK_COUNT_SESSION_STARTED",
  STOCK_COUNT_LINE_SAVED: "STOCK_COUNT_LINE_SAVED",
  STOCK_COUNT_VARIANCE_REVIEW_REQUIRED: "STOCK_COUNT_VARIANCE_REVIEW_REQUIRED",
  STOCK_COUNT_SUBMITTED: "STOCK_COUNT_SUBMITTED",
  STOCK_COUNT_RECOUNT_REQUESTED: "STOCK_COUNT_RECOUNT_REQUESTED",
  STOCK_COUNT_RECOUNT_SUBMITTED: "STOCK_COUNT_RECOUNT_SUBMITTED",
  STOCK_COUNT_EVIDENCE_ACCEPTED: "STOCK_COUNT_EVIDENCE_ACCEPTED",
  STOCK_COUNT_SESSION_APPROVED: "STOCK_COUNT_SESSION_APPROVED",
  STOCK_COUNT_SESSION_CLOSED: "STOCK_COUNT_SESSION_CLOSED",
  STOCK_COUNT_SESSION_CANCELLED: "STOCK_COUNT_SESSION_CANCELLED",
  RECEIVING_CONFIRMED: "RECEIVING_CONFIRMED",
  RECEIVING_BATCH_OPENED: "RECEIVING_BATCH_OPENED",
  RECEIVING_BATCH_STARTED: "RECEIVING_BATCH_STARTED",
  RECEIVING_EXCEPTION_RECORDED: "RECEIVING_EXCEPTION_RECORDED",
  RECEIVING_EXCEPTION_REVIEWED: "RECEIVING_EXCEPTION_REVIEWED",
  RECEIVING_ITEM_ADDED: "RECEIVING_ITEM_ADDED",
  RECEIVING_EVIDENCE_SUBMITTED: "RECEIVING_EVIDENCE_SUBMITTED",
  MARKDOWN_APPLIED: "MARKDOWN_APPLIED",
  LABEL_PRINT_REQUESTED: "LABEL_PRINT_REQUESTED",
  SHELF_TICKET_BATCH_CREATED: "SHELF_TICKET_BATCH_CREATED",
  SHELF_TICKET_SIZE_SELECTED: "SHELF_TICKET_SIZE_SELECTED",
  SHELF_TICKET_ITEM_SCANNED: "SHELF_TICKET_ITEM_SCANNED",
  SHELF_TICKET_ITEM_ADDED: "SHELF_TICKET_ITEM_ADDED",
  SHELF_TICKET_ITEM_REMOVED: "SHELF_TICKET_ITEM_REMOVED",
  SHELF_TICKET_BATCH_SENT_TO_DESKTOP: "SHELF_TICKET_BATCH_SENT_TO_DESKTOP",
  SHELF_TICKET_BATCH_QUEUED_FOR_SYNC: "SHELF_TICKET_BATCH_QUEUED_FOR_SYNC",
  SHELF_TICKET_BATCH_CANCELLED: "SHELF_TICKET_BATCH_CANCELLED",
  SHELF_TICKET_BATCH_RECEIVED_BY_DESKTOP: "SHELF_TICKET_BATCH_RECEIVED_BY_DESKTOP",
  WASTE_RECORDED: "WASTE_RECORDED",
  WASTE_APPROVAL_REQUIRED: "WASTE_APPROVAL_REQUIRED",
  ATTRIBUTE_EVIDENCE_CAPTURED: "ATTRIBUTE_EVIDENCE_CAPTURED",
  WEIGHTED_ITEM_EVIDENCE_CAPTURED: "WEIGHTED_ITEM_EVIDENCE_CAPTURED",
  EXPIRY_CHECK_RECORDED: "EXPIRY_CHECK_RECORDED",
  FRESHNESS_CHECK_RECORDED: "FRESHNESS_CHECK_RECORDED",
  EXPIRY_MARKDOWN_RECOMMENDED: "EXPIRY_MARKDOWN_RECOMMENDED",
  EXPIRY_WASTE_RECOMMENDED: "EXPIRY_WASTE_RECOMMENDED",
  FRESHNESS_REVIEW_REQUIRED: "FRESHNESS_REVIEW_REQUIRED",
  EXPIRY_DATE_UPDATED: "EXPIRY_DATE_UPDATED",
  TASK_CREATED: "TASK_CREATED",
  TASK_STARTED: "TASK_STARTED",
  TASK_COMPLETED: "TASK_COMPLETED",
  TASK_BLOCKED: "TASK_BLOCKED",
  TASK_CANCELLED: "TASK_CANCELLED",
  TASK_REASSIGNED: "TASK_REASSIGNED",
  TASK_ESCALATED: "TASK_ESCALATED",
  TASK_LINKED_ACTION_OPENED: "TASK_LINKED_ACTION_OPENED",
  TASK_FILTER_CHANGED: "TASK_FILTER_CHANGED",
  INVENTORY_SYNC_STARTED: "INVENTORY_SYNC_STARTED",
  INVENTORY_SYNC_SUCCEEDED: "INVENTORY_SYNC_SUCCEEDED",
  INVENTORY_SYNC_FAILED: "INVENTORY_SYNC_FAILED",
  INVENTORY_PULL_STARTED: "INVENTORY_PULL_STARTED",
  INVENTORY_PULL_SUCCEEDED: "INVENTORY_PULL_SUCCEEDED",
  INVENTORY_PULL_FAILED: "INVENTORY_PULL_FAILED",
  INVENTORY_PUSH_STARTED: "INVENTORY_PUSH_STARTED",
  INVENTORY_PUSH_SUCCEEDED: "INVENTORY_PUSH_SUCCEEDED",
  INVENTORY_PUSH_FAILED: "INVENTORY_PUSH_FAILED",
  LOCAL_EVENT_SAVED: "LOCAL_EVENT_SAVED",
  SYNC_QUEUED: "SYNC_QUEUED",
  SYNC_STARTED: "SYNC_STARTED",
  SYNC_SUCCEEDED: "SYNC_SUCCEEDED",
  SYNC_FAILED: "SYNC_FAILED",
  SYNC_RETRY_REQUESTED: "SYNC_RETRY_REQUESTED",
  SYNC_CONFLICT_DETECTED: "SYNC_CONFLICT_DETECTED",
  SYNC_STATUS_VIEWED: "SYNC_STATUS_VIEWED",
  OFFLINE_MODE_ENTERED: "OFFLINE_MODE_ENTERED",
  ONLINE_MODE_RESTORED: "ONLINE_MODE_RESTORED",
  DECISION_RECOMMENDATION_GENERATED: "DECISION_RECOMMENDATION_GENERATED",
  DECISION_RECOMMENDATION_ACCEPTED: "DECISION_RECOMMENDATION_ACCEPTED",
  DECISION_RECOMMENDATION_REJECTED: "DECISION_RECOMMENDATION_REJECTED",
  DECISION_RECOMMENDATION_OVERRIDDEN: "DECISION_RECOMMENDATION_OVERRIDDEN",
  DECISION_SUPERVISOR_REVIEW_REQUIRED: "DECISION_SUPERVISOR_REVIEW_REQUIRED",
  DECISION_TASK_CREATED: "DECISION_TASK_CREATED",
  DECISION_REASON_VIEWED: "DECISION_REASON_VIEWED",
  TRANSFER_STARTED: "TRANSFER_STARTED",
  TRANSFER_BATCH_OPENED: "TRANSFER_BATCH_OPENED",
  TRANSFER_DISPATCH_EVIDENCE_SAVED: "TRANSFER_DISPATCH_EVIDENCE_SAVED",
  TRANSFER_RECEIVE_EVIDENCE_SAVED: "TRANSFER_RECEIVE_EVIDENCE_SAVED",
  TRANSFER_BATCH_SUBMITTED: "TRANSFER_BATCH_SUBMITTED",
  TRANSFER_TYPE_SELECTED: "TRANSFER_TYPE_SELECTED",
  TRANSFER_SOURCE_SELECTED: "TRANSFER_SOURCE_SELECTED",
  TRANSFER_ITEM_SCANNED: "TRANSFER_ITEM_SCANNED",
  TRANSFER_QUANTITY_ENTERED: "TRANSFER_QUANTITY_ENTERED",
  TRANSFER_DESTINATION_SELECTED: "TRANSFER_DESTINATION_SELECTED",
  TRANSFER_REVIEWED: "TRANSFER_REVIEWED",
  TRANSFER_COMPLETED: "TRANSFER_COMPLETED",
  TRANSFER_REQUEST_SUBMITTED: "TRANSFER_REQUEST_SUBMITTED",
  TRANSFER_CANCELLED: "TRANSFER_CANCELLED",
  TRANSFER_EXCEPTION_RECORDED: "TRANSFER_EXCEPTION_RECORDED",
  TRANSFER_QUEUED_FOR_SYNC: "TRANSFER_QUEUED_FOR_SYNC",
  TRANSFER_SUPERVISOR_REVIEW_REQUIRED: "TRANSFER_SUPERVISOR_REVIEW_REQUIRED",
  OPERATIONAL_MENU_OPENED: "OPERATIONAL_MENU_OPENED",
  OPERATIONAL_PANEL_OPENED: "OPERATIONAL_PANEL_OPENED",
  SYNC_NOW_REQUESTED: "SYNC_NOW_REQUESTED",
  UNKNOWN_ITEM_EVIDENCE_CREATED: "UNKNOWN_ITEM_EVIDENCE_CREATED",
  PRODUCT_IDENTITY_REVIEW_VIEWED: "PRODUCT_IDENTITY_REVIEW_VIEWED",
  PRODUCT_IDENTITY_REVIEW_UPDATED: "PRODUCT_IDENTITY_REVIEW_UPDATED",
  PRODUCT_IDENTITY_LINK_APPROVED: "PRODUCT_IDENTITY_LINK_APPROVED",
  PRODUCT_IDENTITY_EVIDENCE_REJECTED: "PRODUCT_IDENTITY_EVIDENCE_REJECTED",
  PRODUCT_IDENTITY_EVIDENCE_ESCALATED: "PRODUCT_IDENTITY_EVIDENCE_ESCALATED",
  PRODUCT_IDENTITY_EVIDENCE_DEFERRED: "PRODUCT_IDENTITY_EVIDENCE_DEFERRED",
  PRODUCT_IDENTITY_PERMISSION_BLOCKED: "PRODUCT_IDENTITY_PERMISSION_BLOCKED",
  SCANNER_TEST_STARTED: "SCANNER_TEST_STARTED",
  SCANNER_TEST_SCANNED: "SCANNER_TEST_SCANNED",
  DEVICE_STATUS_VIEWED: "DEVICE_STATUS_VIEWED",
  AUDIT_EVENTS_VIEWED: "AUDIT_EVENTS_VIEWED",
  SUPERVISOR_OVERRIDE_REQUESTED: "SUPERVISOR_OVERRIDE_REQUESTED",
  SUPERVISOR_OVERRIDE_APPROVED: "SUPERVISOR_OVERRIDE_APPROVED",
  SUPERVISOR_OVERRIDE_BLOCKED: "SUPERVISOR_OVERRIDE_BLOCKED",
  PERMISSION_ATTEMPT_BLOCKED: "PERMISSION_ATTEMPT_BLOCKED",
  SCANOPS_SETTINGS_VIEWED: "SCANOPS_SETTINGS_VIEWED",
  SCANOPS_SETTING_CHANGED: "SCANOPS_SETTING_CHANGED",
  STORE_CONTEXT_CHANGE_BLOCKED: "STORE_CONTEXT_CHANGE_BLOCKED",
  SHELF_TICKET_QUEUE_STATUS_VIEWED: "SHELF_TICKET_QUEUE_STATUS_VIEWED",
  SESSION_ENDED: "SESSION_ENDED",
  SESSION_ROLE_PREVIEW_CHANGED: "SESSION_ROLE_PREVIEW_CHANGED",
};

export function createScanOpsEvent(eventType, payload = {}) {
  const identity = buildEventIdentity(getScanOpsSession());
  const traceId = payload.traceId || payload.trace_id || makeId("trace");
  const event = {
    event_id: makeId("evt"),
    trace_id: traceId,
    traceId,
    event_type: eventType,
    source_module: payload.source_module || "ScanOps",
    user_id: identity.user_id || SCANOPS_USER_CONTEXT.user_id,
    user_name: identity.user_name || SCANOPS_USER_CONTEXT.user_name,
    role: identity.role || SCANOPS_USER_CONTEXT.role,
    scanner_id: identity.scanner_id || SCANOPS_USER_CONTEXT.scanner_id,
    location_id: identity.location_id || SCANOPS_USER_CONTEXT.location_id,
    created_at: identity.created_at,
    timestamp: identity.timestamp,
    actorUserId: identity.actorUserId,
    actorName: identity.actorName,
    actorRole: identity.actorRole,
    deviceId: identity.deviceId,
    scannerId: identity.scannerId,
    storeId: identity.storeId,
    departmentId: identity.departmentId,
    sessionId: identity.sessionId,
    environment: identity.environment,
    status: payload.status || "recorded",
    ...payload,
  };
  const events = safeReadEvents();
  safeWriteEvents([event, ...events].slice(0, 120));
  recordEventForInventorySync(event);
  return event;
}

export function getScanOpsEvents() {
  return safeReadEvents();
}
