export const SCANOPS_BRIDGE_QUEUE_SYNC_PHASE = '7';
export const SCANOPS_BRIDGE_QUEUE_SYNC_COMPONENT = 'scanops_bridge_queue_sync_receipt_processing';
export const SCANOPS_BRIDGE_QUEUE_SYNC_VERSION = 'scanops-queue-sync.v0.7.0';

export const SCANOPS_BRIDGE_QUEUE_SYNC_STATUSES = Object.freeze({
  READY: 'QUEUE_ENVELOPE_READY',
  BLOCKED: 'QUEUE_ENVELOPE_BLOCKED',
  SYNCED: 'SYNCED',
  DUPLICATE: 'DUPLICATE',
  REJECTED: 'REJECTED',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  TRANSPORT_ERROR: 'TRANSPORT_ERROR',
});

export const SCANOPS_BRIDGE_QUEUE_SYNC_BLOCKERS = Object.freeze({
  QUEUE_ITEM_REQUIRED: 'queue_item_required',
  QUEUE_ITEM_ID_REQUIRED: 'queue_item_id_required',
  OPERATION_TYPE_REQUIRED: 'operation_type_required',
  UNSUPPORTED_OPERATION: 'unsupported_queue_operation',
  PAYLOAD_REQUIRED: 'queue_payload_required',
  PAYLOAD_PLAIN_OBJECT_REQUIRED: 'queue_payload_plain_object_required',
  MUTATION_INTENT_BLOCKED: 'mutation_intent_blocked',
});

export const QUEUE_EVENT_TO_OPERATION_TYPE = Object.freeze({
  LOOKUP_REQUEST: 'LOOKUP_REQUEST',
  ITEM_LOOKUP_REQUEST: 'LOOKUP_REQUEST',
  PRODUCT_LOOKUP_REQUEST: 'LOOKUP_REQUEST',
  STOCK_COUNT: 'COUNT_SUBMISSION',
  STOCK_COUNT_LINE_SAVED: 'COUNT_SUBMISSION',
  COUNT_SUBMISSION: 'COUNT_SUBMISSION',
  RECEIVING: 'RECEIVING_SUBMISSION',
  RECEIVING_LINE_SAVED: 'RECEIVING_SUBMISSION',
  RECEIVING_SUBMISSION: 'RECEIVING_SUBMISSION',
  TRANSFER: 'TRANSFER_SUBMISSION',
  TRANSFER_LINE_SAVED: 'TRANSFER_SUBMISSION',
  TRANSFER_SUBMISSION: 'TRANSFER_SUBMISSION',
  WASTE: 'WASTE_SUBMISSION',
  WASTAGE: 'WASTE_SUBMISSION',
  WASTE_LINE_SAVED: 'WASTE_SUBMISSION',
  WASTAGE_LINE_SAVED: 'WASTE_SUBMISSION',
  WASTE_SUBMISSION: 'WASTE_SUBMISSION',
  MARKDOWN: 'MARKDOWN_SUBMISSION',
  MARKDOWN_LINE_SAVED: 'MARKDOWN_SUBMISSION',
  MARKDOWN_SUBMISSION: 'MARKDOWN_SUBMISSION',
  EXPIRY: 'EXPIRY_SUBMISSION',
  EXPIRY_CHECK_LINE: 'EXPIRY_SUBMISSION',
  EXPIRY_LINE_SAVED: 'EXPIRY_SUBMISSION',
  EXPIRY_SUBMISSION: 'EXPIRY_SUBMISSION',
  MOVEMENT_NOTE: 'MOVEMENT_NOTE',
  MOVEMENT_NOTE_SAVED: 'MOVEMENT_NOTE',
  DEVICE_HEALTH: 'DEVICE_HEALTH_PING',
  DEVICE_HEALTH_PING: 'DEVICE_HEALTH_PING',
});

export const MUTATION_INTENT_KEYS = Object.freeze([
  'inventoryDirectWrite',
  'inventory_direct_write',
  'directInventoryWrite',
  'direct_inventory_write',
  'ledgerMutation',
  'ledger_mutation',
  'stockMutation',
  'stock_mutation',
  'priceMutation',
  'price_mutation',
  'approvalAction',
  'approval_action',
]);
