import React, { useMemo, useState } from "react";
import PageHeader from "../components/scanner/PageHeader";
import { useToast } from "@/components/ui/use-toast";
import { CheckCircle2, Database, Eye, RefreshCw, RotateCw, Wifi, WifiOff } from "lucide-react";
import { createScanOpsEvent, SCANOPS_EVENT_TYPES } from "../lib/scanOpsEvents";
import { getInventoryConnection, getLocalInventorySnapshot, pullInventorySnapshot } from "../lib/inventorySystemAdapter";
import { getSyncQueue, getSyncSummary, retryAllSyncEvents, retrySyncEvent, setNetworkMode, SYNC_STATUSES } from "../lib/scanOpsSync";

const BUTTON_PRIMARY = "w-full py-4 rounded-2xl bg-primary text-primary-foreground font-bold text-sm active:scale-[0.98] transition-all flex items-center justify-center gap-2 disabled:opacity-40";
const BUTTON_SECONDARY = "w-full py-4 rounded-2xl bg-secondary text-secondary-foreground font-bold text-sm active:scale-[0.98] active:bg-border transition-all flex items-center justify-center gap-2";
const MINI_BUTTON = "px-3 py-2.5 rounded-xl bg-secondary text-secondary-foreground text-xs font-bold active:scale-[0.98] active:bg-border transition-all flex items-center justify-center gap-1.5";
function formatTime(value) { if (!value) return "Never"; try { return new Date(value).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }); } catch { return value; } }
function statusTone(status) { if (status === SYNC_STATUSES.SYNCED) return "bg-accent/10 border-accent/20 text-accent"; if ([SYNC_STATUSES.FAILED, SYNC_STATUSES.CONFLICT, SYNC_STATUSES.NEEDS_REVIEW].includes(status)) return "bg-destructive/10 border-destructive/20 text-destructive"; if ([SYNC_STATUSES.QUEUED, SYNC_STATUSES.SYNCING].includes(status)) return "bg-primary/10 border-primary/20 text-primary"; return "bg-secondary border-border text-muted-foreground"; }

export default function InventorySync() {
  const { toast } = useToast();
  const [queue, setQueue] = useState(() => getSyncQueue());
  const [connection, setConnection] = useState(() => getInventoryConnection());
  const [snapshot, setSnapshot] = useState(() => getLocalInventorySnapshot());
  const [selected, setSelected] = useState(null);
  const summary = useMemo(() => getSyncSummary(), [queue]);
  const refreshState = () => { setQueue(getSyncQueue()); setConnection(getInventoryConnection()); setSnapshot(getLocalInventorySnapshot()); };
  const handleMode = (mode) => { const next = setNetworkMode(mode); setConnection(next); createScanOpsEvent(mode === "offline" ? SCANOPS_EVENT_TYPES.OFFLINE_MODE_ENTERED : SCANOPS_EVENT_TYPES.ONLINE_MODE_RESTORED, { source_module: "Inventory Sync", status: mode, adapter: next.adapterName }); toast({ description: mode === "offline" ? "Demo offline mode enabled" : "Demo online mode restored", duration: 1500 }); refreshState(); };
  const handlePull = () => { createScanOpsEvent(SCANOPS_EVENT_TYPES.INVENTORY_PULL_STARTED, { source_module: "Inventory Sync", status: "started" }); const result = pullInventorySnapshot(); createScanOpsEvent(result.ok ? SCANOPS_EVENT_TYPES.INVENTORY_PULL_SUCCEEDED : SCANOPS_EVENT_TYPES.INVENTORY_PULL_FAILED, { source_module: "Inventory Sync", status: result.ok ? "synced" : "failed", reason: result.error, item_count: result.snapshot?.items?.length }); toast({ description: result.ok ? "Inventory snapshot pulled" : "Pull failed while offline", duration: 1500 }); refreshState(); };
  const handleRetry = (id) => { createScanOpsEvent(SCANOPS_EVENT_TYPES.SYNC_RETRY_REQUESTED, { source_module: "Inventory Sync", status: "requested", sync_record_id: id }); const result = retrySyncEvent(id); setSelected(result || selected); refreshState(); toast({ description: result?.status === SYNC_STATUSES.SYNCED ? "Event synced" : "Retry completed", duration: 1500 }); };
  const handleRetryAll = () => { createScanOpsEvent(SCANOPS_EVENT_TYPES.INVENTORY_PUSH_STARTED, { source_module: "Inventory Sync", status: "started" }); const results = retryAllSyncEvents(); const synced = results.filter((item) => item?.status === SYNC_STATUSES.SYNCED).length; createScanOpsEvent(synced > 0 ? SCANOPS_EVENT_TYPES.INVENTORY_PUSH_SUCCEEDED : SCANOPS_EVENT_TYPES.INVENTORY_PUSH_FAILED, { source_module: "Inventory Sync", status: synced > 0 ? "synced" : "failed_or_waiting", synced_count: synced, attempted_count: results.length }); refreshState(); toast({ description: synced > 0 ? `${synced} event${synced === 1 ? "" : "s"} synced` : "No events synced", duration: 1500 }); };
  if (selected) return <SyncDetail record={selected} onBack={() => { setSelected(null); refreshState(); }} onRetry={() => handleRetry(selected.id)} />;
  return (
    <div className="min-h-screen bg-background flex flex-col overflow-x-hidden"><PageHeader title="Inventory Sync" subtitle="Stage G · PLU / GTIN / SKU sync foundation" /><main className="flex-1 px-4 py-5 pb-8 space-y-4 overflow-y-auto overflow-x-hidden">
      <section className="bg-card rounded-2xl border border-border p-5 min-w-0"><div className="flex items-start gap-3"><div className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 ${connection.mode === "offline" ? "bg-destructive/10 text-destructive" : "bg-accent/10 text-accent"}`}>{connection.mode === "offline" ? <WifiOff className="w-5 h-5" /> : <Wifi className="w-5 h-5" />}</div><div className="min-w-0 flex-1"><p className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Connection</p><h2 className="text-lg font-bold text-foreground mt-1 break-words">{connection.statusLabel}</h2><p className="text-sm text-muted-foreground mt-1 break-words">Inventory remains the source of truth. ScanOps saves local events and pushes them when connection is available.</p></div></div><div className="grid grid-cols-2 gap-2 mt-4"><button onClick={() => handleMode("offline")} className={BUTTON_SECONDARY}><WifiOff className="w-4 h-4" />Simulate Offline</button><button onClick={() => handleMode("online")} className={BUTTON_SECONDARY}><Wifi className="w-4 h-4" />Simulate Online</button></div></section>
      <section className="grid grid-cols-2 gap-3"><Metric label="Queued" value={summary.queued} /><Metric label="Failed" value={summary.failed} danger={summary.failed > 0} /><Metric label="Conflicts" value={summary.conflict} danger={summary.conflict > 0} /><Metric label="Synced" value={summary.synced} good /></section>
      <section className="bg-card rounded-2xl border border-border p-5 min-w-0"><div className="flex items-start gap-3"><div className="w-10 h-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center shrink-0"><Database className="w-5 h-5" /></div><div className="min-w-0 flex-1"><p className="text-xs font-bold text-primary uppercase tracking-wider">Inventory snapshot</p><h3 className="text-base font-bold text-foreground mt-1 break-words">{snapshot.items.length} items cached</h3><p className="text-sm text-muted-foreground mt-1 break-words">PLU, GTIN/barcode, SKU, scale code, locations, prices, stock, and fresh-batch data.</p><div className="grid grid-cols-2 gap-2 mt-4"><SmallFact label="PLU items" value={snapshot.items.filter((item) => item.plu).length} /><SmallFact label="Fresh items" value={snapshot.items.filter((item) => ["Produce", "Fresh Meat", "Seafood", "Dairy"].includes(item.department)).length} /><SmallFact label="Near expiry" value={snapshot.items.filter((item) => String(item.freshnessStatus || "").toLowerCase().includes("expiry") || String(item.freshnessStatus || "").toLowerCase().includes("expired")).length} /><SmallFact label="Low stock" value={snapshot.items.filter((item) => Number(item.shelfStock || 0) <= Number(item.minimumStock || 0)).length} /></div></div></div><div className="grid grid-cols-2 gap-2 mt-4"><button onClick={handlePull} className={BUTTON_PRIMARY}><RefreshCw className="w-4 h-4" />Pull Inventory</button><button onClick={handleRetryAll} className={BUTTON_SECONDARY}><RotateCw className="w-4 h-4" />Push Queue</button></div><p className="text-xs text-muted-foreground mt-3">Last pull: {formatTime(connection.lastPullAt || snapshot.pulledAt)} · Last push: {formatTime(connection.lastPushAt)}</p></section>
      <section className="space-y-3 min-w-0"><div className="flex items-center justify-between gap-3"><h2 className="text-sm font-bold text-foreground">Sync Queue</h2><p className="text-xs text-muted-foreground">{queue.length} local record{queue.length === 1 ? "" : "s"}</p></div>{queue.length === 0 ? <div className="bg-card rounded-2xl border border-border p-6 text-center"><CheckCircle2 className="w-10 h-10 text-accent mx-auto" /><p className="text-sm font-bold text-foreground mt-3">No local sync records yet</p><p className="text-xs text-muted-foreground mt-1">Complete a task or scanner workflow while offline to create queued inventory work.</p></div> : queue.map((record) => <SyncCard key={record.id} record={record} onView={() => setSelected(record)} onRetry={() => handleRetry(record.id)} />)}</section>
    </main></div>
  );
}
function Metric({ label, value, danger = false, good = false }) { return <div className={`${danger ? "bg-destructive/5 border-destructive/20" : good ? "bg-accent/5 border-accent/20" : "bg-card border-border"} rounded-2xl border p-4 min-w-0`}><p className="text-xs font-bold text-muted-foreground uppercase tracking-wider">{label}</p><p className="text-3xl font-black text-foreground mt-1">{value}</p></div>; }
function SmallFact({ label, value }) { return <div className="rounded-2xl bg-secondary/60 px-3 py-3 min-w-0"><p className="text-[11px] font-bold text-muted-foreground uppercase tracking-wider">{label}</p><p className="text-base font-bold text-foreground mt-1">{value}</p></div>; }
function SyncCard({ record, onView, onRetry }) { const retryable = record.status !== SYNC_STATUSES.SYNCED; return <section className="bg-card rounded-2xl border border-border p-4 min-w-0"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><span className={`inline-flex rounded-full border px-2.5 py-1 text-[11px] font-bold uppercase tracking-wider ${statusTone(record.status)}`}>{record.statusLabel}</span><h3 className="text-sm font-bold text-foreground mt-3 break-words">{record.eventType}</h3><p className="text-xs text-muted-foreground mt-1 break-words">{record.payloadSummary}</p>{record.failureReason && <p className="text-xs font-semibold text-destructive mt-2 break-words">{record.failureReason}</p>}</div><div className="text-right shrink-0"><p className="text-xs font-mono text-muted-foreground">#{record.attemptCount || 0}</p><p className="text-[11px] text-muted-foreground mt-1">tries</p></div></div><div className="grid grid-cols-2 gap-2 mt-4"><button onClick={onView} className={MINI_BUTTON}><Eye className="w-3.5 h-3.5" />View</button><button onClick={onRetry} disabled={!retryable} className={`${MINI_BUTTON} disabled:opacity-40`}><RotateCw className="w-3.5 h-3.5" />Retry</button></div></section>; }
function SyncDetail({ record, onBack, onRetry }) { const rows = [["Status", record.statusLabel], ["Local Event ID", record.localEventId], ["Inventory Event ID", record.inventoryEventId || "Pending"], ["Source", record.sourceModule], ["Device", record.deviceId], ["Location", record.locationId], ["Saved", formatTime(record.createdAt)], ["Last attempt", formatTime(record.lastAttemptAt)]]; return <div className="min-h-screen bg-background flex flex-col overflow-x-hidden"><PageHeader title="Sync Event Detail" subtitle={record.eventType} /><main className="flex-1 px-4 py-5 pb-8 space-y-4 overflow-y-auto overflow-x-hidden"><section className="bg-card rounded-2xl border border-border p-5 min-w-0"><span className={`inline-flex rounded-full border px-2.5 py-1 text-[11px] font-bold uppercase tracking-wider ${statusTone(record.status)}`}>{record.statusLabel}</span><h2 className="text-lg font-bold text-foreground mt-3 break-words">{record.eventType}</h2><p className="text-sm text-muted-foreground mt-1 break-words">{record.payloadSummary}</p></section><section className="bg-card rounded-2xl border border-border divide-y divide-border min-w-0">{rows.map(([label, value]) => <div key={label} className="flex items-start justify-between gap-4 px-5 py-3.5"><span className="text-sm text-muted-foreground shrink-0">{label}</span><span className="text-sm font-semibold text-foreground text-right break-words min-w-0">{value}</span></div>)}</section><section className="bg-card rounded-2xl border border-border p-5 min-w-0"><p className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Sync history</p><div className="space-y-3 mt-3">{(record.syncHistory || []).map((entry, index) => <div key={`${entry.at}-${index}`} className="rounded-2xl bg-secondary/60 px-3 py-3"><p className="text-xs font-bold text-foreground">{entry.label}</p><p className="text-xs text-muted-foreground mt-1 break-words">{entry.message}</p><p className="text-[11px] text-muted-foreground mt-1">{formatTime(entry.at)}</p></div>)}</div></section><div className="space-y-3"><button onClick={onRetry} disabled={record.status === SYNC_STATUSES.SYNCED} className={BUTTON_PRIMARY}><RotateCw className="w-4 h-4" />Retry Sync</button><button onClick={onBack} className={BUTTON_SECONDARY}>Back to Inventory Sync</button></div></main></div>; }
