import { createBridgePhase34InventoryApplicationBoundaryPlan } from "./bridgePhase34InventoryApplicationBoundaryPlan";

export function createBridgePhase34ReceiptIdempotencyPlan() {
  const inventoryApplicationBoundaryPlan = createBridgePhase34InventoryApplicationBoundaryPlan();

  return Object.freeze({
    phase: "34.receipt-shape-and-idempotency-planning",
    status: "receipt-shape-idempotency-planning-only",
    inventoryApplicationBoundaryPlan,
    scope: Object.freeze({
      planningOnly: true,
      definesRuntimeTypes: false,
      activatesRuntime: false,
      executesFixtures: false,
      enablesTransport: false,
      enablesPersistence: false,
      processesQueues: false,
      mutatesInventory: false,
      mutatesScanOps: false,
    }),
    receiptIdentityPlan: Object.freeze({
      receiptIdRequired: true,
      idempotencyKeyRequired: true,
      payloadHashRequired: true,
      traceIdRequired: true,
      duplicateDetectionRequiredBeforeProcessing: true,
      repeatedReceiptMustNotApplyTwice: true,
      environmentIncludedInIdentity: true,
      sourceDeviceIncludedInIdentity: true,
      sourceSessionIncludedInIdentity: true,
    }),
    plannedReceiptEnvelopeFields: Object.freeze([
      "receiptId",
      "idempotencyKey",
      "payloadHash",
      "traceId",
      "sourceEnvironment",
      "sourceDeviceId",
      "sourceSessionId",
      "sourceScannerId",
      "sourceWorkflow",
      "operatorId",
      "operatorRole",
      "storeId",
      "departmentId",
      "createdAt",
      "schemaVersion",
    ]),
    plannedReceiptPayloadSections: Object.freeze([
      "workflowIntent",
      "scanEvidence",
      "operatorConfirmation",
      "exceptionFlags",
      "localSnapshotReferences",
      "attachmentsOrEvidenceReferences",
      "supervisorReviewHints",
    ]),
    plannedIdempotencyRules: Object.freeze({
      sameIdempotencyKeyAndSamePayloadHashIsDuplicate: true,
      sameIdempotencyKeyAndDifferentPayloadHashRequiresReview: true,
      missingIdempotencyKeyRequiresRejection: true,
      missingPayloadHashRequiresRejection: true,
      liveEnvironmentReceiptsBlockedUntilExplicitLiveScope: true,
      testTrainingReceiptsRemainNonProduction: true,
      duplicateReceiptCannotAdvanceToApplication: true,
      manualReviewRequiredForConflict: true,
    }),
    plannedReceiptValidationStates: Object.freeze([
      "received",
      "identity-validated",
      "duplicate-detected",
      "payload-conflict",
      "environment-blocked",
      "schema-invalid",
      "needs-review",
      "validated-for-inventory-review",
      "rejected",
    ]),
    plannedFailureHandlingRules: Object.freeze({
      validationFailureDoesNotRetryInBackground: true,
      duplicateDetectionDoesNotApplyInventoryChanges: true,
      payloadConflictDoesNotApplyInventoryChanges: true,
      environmentBlockDoesNotApplyInventoryChanges: true,
      operatorStatusMustRemainHonest: true,
      failureRequiresAuditCorrelation: true,
      futureRetryMustBeManualAndScoped: true,
    }),
    forbiddenBehaviors: Object.freeze([
      "create runtime transport contract",
      "execute fixtures",
      "persist receipts",
      "process queues",
      "apply Inventory changes",
      "auto-advance duplicate receipts",
      "auto-retry failed receipts in background",
      "mark receipt applied without Inventory confirmation",
      "treat TEST or TRAINING receipt as LIVE",
    ]),
    readinessVerdict: Object.freeze({
      receiptShapePlanningDefined: true,
      idempotencyPlanningDefined: true,
      safeToMergeAsPlanningOnly: true,
      safeToExecuteFixturesNow: false,
      safeToActivateTransportNow: false,
      safeToEnablePersistenceNow: false,
      safeToProcessQueuesNow: false,
      safeToApplyInventoryChangesNow: false,
      safeToActivateLiveNow: false,
    }),
    nextAllowedStep: "phase-34-operator-safe-status-planning",
  });
}
