import { createBridgePhase34TransportContractPlan } from "./bridgePhase34TransportContractPlan";

export function createBridgePhase34PersistenceQueueContractPlan() {
  const transportContractPlan = createBridgePhase34TransportContractPlan();

  return Object.freeze({
    phase: "34.persistence-queue-contract-planning",
    status: "persistence-queue-contract-planning-only",
    transportContractPlan,
    scope: Object.freeze({
      planningOnly: true,
      persistenceContractOnly: true,
      queueContractOnly: true,
      activatesRuntime: false,
      executesFixtures: false,
      activatesTransport: false,
      enablesPersistence: false,
      processesQueues: false,
      mutatesInventory: false,
      mutatesScanOps: false,
    }),
    persistenceContractPurpose: Object.freeze({
      defineFuturePersistenceBoundaries: true,
      defineAppendOnlyEvidenceRequirements: true,
      defineEnvironmentGateRequirements: true,
      defineFailureStateRequirements: true,
      enablePersistenceNow: false,
    }),
    queueContractPurpose: Object.freeze({
      defineFutureQueueBoundaries: true,
      defineManualProcessingRequirements: true,
      defineIdempotencyRequirements: true,
      defineNoBackgroundProcessingRequirements: true,
      processQueuesNow: false,
    }),
    plannedPersistenceEnvelopeFields: Object.freeze([
      "receiptId",
      "idempotencyKey",
      "payloadHash",
      "traceId",
      "sourceEnvironment",
      "sourceDeviceId",
      "sourceSessionId",
      "evidenceCreatedAt",
      "persistenceState",
      "schemaVersion",
    ]),
    plannedQueueEnvelopeFields: Object.freeze([
      "queueItemId",
      "receiptId",
      "idempotencyKey",
      "payloadHash",
      "traceId",
      "sourceEnvironment",
      "queueState",
      "createdAt",
      "lastManualActionAt",
      "schemaVersion",
    ]),
    plannedPersistenceSafetyRules: Object.freeze({
      testOrTrainingOnly: true,
      livePersistenceBlocked: true,
      appendOnlyEvidenceOnly: true,
      noInventoryApplicationFromPersistence: true,
      noStockMutationFromPersistence: true,
      noLedgerMutationFromPersistence: true,
      noPricingMutationFromPersistence: true,
      noApprovalMutationFromPersistence: true,
    }),
    plannedQueueSafetyRules: Object.freeze({
      testOrTrainingOnly: true,
      liveQueueProcessingBlocked: true,
      manualScopedProcessingOnly: true,
      noAutomaticProcessing: true,
      noBackgroundReplay: true,
      duplicateDetectionBeforeProcessing: true,
      inventoryReviewBoundaryRequired: true,
      noInventoryApplicationFromQueue: true,
    }),
    plannedQueueStates: Object.freeze([
      "not-created",
      "queued-for-test-training-review",
      "environment-blocked",
      "duplicate-detected",
      "needs-review",
      "ready-for-manual-processing",
      "processed-for-review",
      "failed-without-background-replay",
    ]),
    blockedNow: Object.freeze({
      liveActivation: true,
      fixtureExecution: true,
      transportActivation: true,
      persistenceWrites: true,
      queueProcessing: true,
      inboxProcessing: true,
      inventoryMutation: true,
      scanOpsMutation: true,
      automaticProcessing: true,
    }),
    readinessVerdict: Object.freeze({
      persistenceQueueContractPlanningDefined: true,
      safeToMergeAsPlanningOnly: true,
      safeToExecuteFixturesNow: false,
      safeToActivateTransportNow: false,
      safeToEnablePersistenceNow: false,
      safeToProcessQueuesNow: false,
      safeToApplyInventoryChangesNow: false,
      safeToActivateLiveNow: false,
    }),
    nextAllowedStep: "phase-34-readiness-closeout-summary",
  });
}
