import { createBridgePhase34ControlledFixtureCatalogPlan } from "./bridgePhase34ControlledFixtureCatalogPlan";

export function createBridgePhase34TransportContractPlan() {
  const fixtureCatalogPlan = createBridgePhase34ControlledFixtureCatalogPlan();

  return Object.freeze({
    phase: "34.transport-contract-planning",
    status: "transport-contract-planning-only",
    fixtureCatalogPlan,
    scope: Object.freeze({
      planningOnly: true,
      transportContractOnly: true,
      activatesRuntime: false,
      activatesTransport: false,
      executesFixtures: false,
      enablesPersistence: false,
      processesQueues: false,
      mutatesInventory: false,
      mutatesScanOps: false,
    }),
    transportContractPurpose: Object.freeze({
      defineFutureTransportBoundaries: true,
      defineEnvironmentGateRequirements: true,
      defineFailureStatusRequirements: true,
      defineManualExecutionRequirements: true,
      activateTransportNow: false,
    }),
    plannedTransportEnvelopeFields: Object.freeze([
      "transportId",
      "receiptId",
      "idempotencyKey",
      "payloadHash",
      "traceId",
      "sourceEnvironment",
      "sourceDeviceId",
      "sourceSessionId",
      "targetBoundary",
      "createdAt",
      "schemaVersion",
    ]),
    plannedTransportSafetyRules: Object.freeze({
      testOrTrainingOnly: true,
      liveTransportBlocked: true,
      transportOffByDefault: true,
      manualScopedExecutionOnly: true,
      noAutomaticReplay: true,
      noImplicitPersistence: true,
      noImplicitQueueProcessing: true,
      noInventoryApplicationFromTransport: true,
    }),
    plannedTransportStates: Object.freeze([
      "not-created",
      "prepared-for-test-training",
      "environment-blocked",
      "ready-for-manual-send",
      "sent",
      "received-for-review",
      "failed-without-automatic-replay",
    ]),
    futureTransportValidationChecklist: Object.freeze({
      environmentValidatedBeforeSend: true,
      idempotencyKeyIncluded: true,
      payloadHashIncluded: true,
      traceIdIncluded: true,
      receiptIdentityIncluded: true,
      operatorStatusMapped: true,
      failureOutcomeMapped: true,
      noMutationAssertionIncluded: true,
    }),
    blockedNow: Object.freeze({
      liveActivation: true,
      fixtureExecution: true,
      transportActivation: true,
      persistenceWrites: true,
      queueProcessing: true,
      inboxProcessing: true,
      inventoryMutation: true,
      scanOpsMutation: true,
      automaticProcessing: true,
    }),
    readinessVerdict: Object.freeze({
      transportContractPlanningDefined: true,
      safeToMergeAsPlanningOnly: true,
      safeToExecuteFixturesNow: false,
      safeToActivateTransportNow: false,
      safeToEnablePersistenceNow: false,
      safeToProcessQueuesNow: false,
      safeToApplyInventoryChangesNow: false,
      safeToActivateLiveNow: false,
    }),
    nextAllowedStep: "phase-34-persistence-queue-contract-planning",
  });
}
